[package]
name = "spirv_headers"
version = "1.4.2"
authors = ["Lei Zhang <antiagainst@gmail.com>"]
edition = "2018"

description = "Rust definition of SPIR-V structs and enums"
documentation = "https://docs.rs/spirv_headers"
repository = "https://github.com/gfx-rs/rspirv"
readme = "README.md"
license = "Apache-2.0"
keywords = ["spirv", "definition", "struct", "enum"]

[lib]
path = "lib.rs"

[dependencies]
bitflags = "1"
num-traits = "0.2"
serde = {version = "1", optional = true, features = ["derive"]}
